roi:
  centering: True
  height: 480
# this value is used in the input depth map to indicate that
# depth of the specific pixel is unknown
unknown_pixel_value: 0
# size of the median filter, used for each sector
median_filter_size: 10
