name: simulation
startup_window: odometry
pre_window: export UAV_NAME=uav1; export SIMULATION=true
windows:
  - gazebo:
      layout: even-vertical
      panes:
        - roslaunch mrs_bumper simulation.launch gui:=true
  - spawn:
      layout: even-vertical
      panes:
        - waitForSimulation; spawn 1 --run --delete --enable-rangefinder --enable-rangefinder-up --enable-ground-truth --enable-realsense-front --enable-realistic-realsense --enable-rplidar
  - odometry:
      layout: even-vertical
      panes:
        - waitForOdometry; roslaunch mrs_uav_manager simulation_f550_gps.launch
  - takeoff:
      layout: even-vertical
      panes:
        #{ takeoff uav1
        - 'waitForControl;
          rosservice call /$UAV_NAME/mavros/cmd/arming 1;
          rosservice call /$UAV_NAME/mavros/set_mode 0 offboard;
          rosservice call /$UAV_NAME/control_manager/motors 1;
          rosservice call /$UAV_NAME/uav_manager/takeoff;
          rosservice call /$UAV_NAME/constraint_manager/set_constraints darpa;
          sleep 5;
          rosservice call /$UAV_NAME/control_manager/goto "goal: [-3.5, 3.5, 1.0, -1.57]";
          history -s rosservice call /$UAV_NAME/control_manager/goto "\"goal: [-5.0, 0.0, 2.0, 0.0]\""
          '
        #}
  - mrs_bumper:
      layout: even-vertical
      panes:
        - waitForRos; roslaunch mrs_bumper bumper.launch
        - waitForRos; rostopic echo /uav1/bumper/obstacle_sectors
  - rviz:
      layout: even-vertical
      panes:
        - waitForOdometry; rosrun tf2_ros static_transform_publisher 0 0 0 0 0 0 fcu_uav1 fcu_uav1_horizontal
        - waitForOdometry; roslaunch mrs_bumper rviz_uav1.launch
  - joystic:
      layout: even-vertical
      panes:
        - waitForControl; roslaunch mrs_general logitech_joystick.launch
  - gazebo_camera_follow:
      layout: even-vertical
      panes:
        - waitForOdometry; gz camera -c gzclient_camera -f uav1; history -s gz camera -c gzclient_camera -f uav1
        - waitForControl; ~/.i3/layout_manager.sh simulation
